Specifiche architetturali
iota97/WinningSoftwareSolution pull request #105
Opened 2022-04-03 17:23 UTC by EliaScandaletti

2022-04-05 08:10 UTC, Rolivier1565 commented on docs/esterni/specifiche_architetturali/specifiche_architetturali.tex
> +    \item \underline{\href{https://github.com/iota97/WinningSoftwareSolution/blob/main/public/esterni/verbali/2021_01_03_E.pdf}{Verbale esterno 2021/03/01}}.
Il link è sbagliato, dovrebbe essere 2022

2022-04-05 09:21 UTC, Rolivier1565 requested changes

2022-04-05 09:21 UTC, Rolivier1565 commented on docs/esterni/specifiche_architetturali/specifiche_architetturali.tex
> +    Se chiamata, restituisce tramite \textit{upkeepNeeded} se è passato l'intervallo di tempo minimo dall'ultimo upkeep e dunque se è necessario per formarne un altro.\\
_per formarne_ in senso _to perform_?
In tal caso direi _eseguirne_

2022-04-05 09:21 UTC, Rolivier1565 commented on docs/esterni/specifiche_architetturali/specifiche_architetturali.tex
> +Mostra cosa succede quando viene create una nuova transazione.
```suggestion
Mostra cosa succede quando viene creata una nuova transazione.
```

2022-04-05 09:21 UTC, Rolivier1565 commented on docs/esterni/specifiche_architetturali/specifiche_architetturali.tex
> +Mostra cosa succede quando viene inserito una nuova entry di pagamento da parte di un e-commerce.
```suggestion
Mostra cosa succede quando viene inserita una nuova entry di pagamento da parte di un e-commerce.
```

2022-04-06 07:01 UTC, nicoalbe reviewed
bene

2022-04-07 06:50 UTC, Rolivier1565 approved these changes

2022-04-07 06:55 UTC, merged