Manuale Installazione
iota97/WinningSoftwareSolution pull request #120
Opened 2022-04-13 11:46 UTC by fedemarchits

2022-04-20 06:51 UTC, galvagnimatteo requested changes
Aggiungerei la versione dei software utilizzati

2022-04-20 07:18 UTC, iota97 requested changes

2022-04-20 07:18 UTC, iota97 commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +\end{lstlisting}
Andrebbe messo come collegare l'upkeeper di chainlink (trovi in fondo al readme del server mooolto abbozzato)

2022-04-20 07:18 UTC, iota97 commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +  \item \textbf{SERVER\_URL}: strutturare il server url come segue:
Metamask richiede una connessione HTTPS nella versione mobile. URL del server in HTTPS dovrà essere messo nella variabile SERVER_URL.

Tuttavia per facilitare lo sviluppo e il testing locale l'app Android di Metamask ha inserito nel proprio manifest una whitelist per le connesione HTTP provenienti dal dominio sslip.io

Il servizio sslip.io permette a un qualunque URL nella forma IP_ADDR.sslip.io di venir risolto dai server DNS come IP_ADDR.

É possibile collegarsi al proprio server locale i HTTP quindi usando ad esempio 192.168.0.15:8080.sslip.io

Il supporto ai DeepLink di metamask richiede cmq che puntino a un indirizzo HTTPS, sarà dunque sufficiente passare prima per tinyurl che non solo fornisce pagine HTTPS ma mantiente eventuali aggiunte all'URL quali pagine e parametri GET.

2022-04-20 07:18 UTC, iota97 commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +Per poter utilizzare la webbapp è necessario metamask. Visitare \href{https://www.metamask.io}{metamask.io} per maggiori informazioni.\\\\
webBapp

2022-04-20 07:18 UTC, iota97 commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +  $ truffle deploy --netowrk <YOUR_NETWORK>
`--netowrk`?

2022-04-20 07:18 UTC, iota97 commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +  $ truffle deploy --netowrk <YOUR_NETWORK> --reset --compile-none
`--netowrk`

2022-04-20 07:35 UTC, galvagnimatteo requested changes

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +Installare il database \href{https://mariadb.org/download/}{MariaDB} se non è gia stato installato precedentemente. Una volta eseguita l'installazione del database, collegarsi con il comando:
"gia"

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +Per ottenere il provider per la testnet di Polygon Mumbai è necessario registrarsi su \href{https://www.moralis.io}{moralis.io}. Una volta effettuata la registrazione:
Aggiungerei anche il fatto che la procedura è identica per l'utilizzo in mainnet, dopotutto il manuale di installazione dovrebbe essere "realistico", mumbai è la rete di test che usiamo noi appunto per i test non per il deployment. Tuttavia per usare la mainnet serve pagare e noi non lo faremo, quindi includerei entrambe le cose spiegando come funziona per la mainnet e poi aggiungendo qualcosa come "è possibile anche usare la testnet per testare il corretto funzionamento senza pagare"

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +Nell'url copiato è possibile visualizzare le api key, si tratta infatti del codice evidenziato in grassetto nel seguente esempio:\\\\
LA api key, è solo una

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +È necessario salvare l'url e le api key per i passi successivi.
Same thing. se ti salvi l'url per forza hai salvato anche l'api key, non serve specificarlo imo

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +Una volta inseriti i dati e aggiunto il network, ricordare di selezionare il network.
Tante ripetizioni di "network", si può dire benissimo "la rete" in italiano

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +Per poter utilizzare la webbapp è necessario metamask. Visitare \href{https://www.metamask.io}{metamask.io} per maggiori informazioni.\\\\
Allora, come manuale di installazione mi sembra un po' scarno. Come si crea un wallet? Scriviamo che si può usare metamask ma in realtà un wallet può già essere in possesso dell'azienda o essere creato con altri software e anche offline. Scriviamo che è necessario arrivare ad avere la mnemonica di un wallet, poi a come ci si arriva si fa l'esempio (scrivendo esattamente come fare) con metamask e dicendo che si può fare in altro modo anche imo

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +Per l'inserimento e la configurazione del network Mumbai nel proprio wallet Metamask è necessario utilizzare i seguenti dati:
rete, non network che fa bruttino

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +\item Block Explorer URL: \textbf{https://polygonscan.com/}.
Bisogna scegliere: se spieghiamo come fare sulla mainnet il block explorer è quello, se spieghiamo come fare sulla testnet è mumbai.polygonscan.com. Either way consiglio di descrivere entrambi i casi, se si sta installando per test mumbai se invece seriamente mainnet polygon

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +  \item \textbf{SERVER\_URL}: strutturare il server url come segue:
Dici strutturare SERVER_URL come segue e poi dici di fare un passo in più. Direi piuttosto, SERVER_URL: va creato tramite tinyurl un link che punta all'url nel formato ip.sslip.io o simili

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +  \item installare le seguenti dipendenze:
Aggiungere come si installano queste dipendenze. Fai sempre conto che l'utente/l'ecommerce sappia ben poco e gli serva la spiegazione più dettagliata possibile, quindi nessun comando deve essere inteso implicitamente

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +È possibile realizzare un proprio script in python per la vendita di prodotti.\\
Non proprio, cioè sì ma non solo. Piuttosto, "è possibile includere lo script in python nel backend dell'ecommerce al momento della messa in vendita chiamando la funzione ecc ecc"

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +  \item \textbf{apikey.secret}: deve contenere le api key ottenibili come spiegato al punto \hyperref[sec:provider]{2.1.2}.
LA api key

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +  \item \textbf{apikey.secret}: deve contenere le api key ottenibili come spiegato al punto \hyperref[sec:provider]{2.1.2}.
Poi in realtà no, la api key in quel file non è quella del provider. la api key in quel file la si ottiene andando su polygon scan e creando un account e copiando la chiave api, perchè serve solo a verificare il contratto su polygonscan. quella fornita dal provider sta in provider.secret nel link.

2022-04-20 07:35 UTC, galvagnimatteo commented on docs/esterni/manuale_installazione/manuale_installazione.tex
> +  $ truffle deploy --netowrk <YOUR_NETWORK>
Da qui in poi, "netowrk" in ogni comando è sbagliato

2022-04-20 07:42 UTC, galvagnimatteo commented
Also, cambia nome del file e del documento in manuale sviluppatore che ha più senso

2022-04-26 17:49 UTC, galvagnimatteo submitted a review, later dismissed

2022-04-26 17:57 UTC, merged