Chiusura sprint6
iota97/WinningSoftwareSolution pull request #189
Opened 2022-05-05 09:39 UTC by avolpe1998

2022-05-05 10:15 UTC, iota97 commented on docs/esterni/piano_di_progetto/piano_di_progetto.tex
>  \ganttbar[progress=0]{Validazione}{2022-04-27}{2022-05-11}
Sposta l'inizio di questo anche che poi ci dimentichiamo

2022-05-07 08:38 UTC, nicoalbe requested changes
La somma delle ore totali nel preventivo generale e preventivo ciclo sei sono sbagliate di una unità: 71 e non 72, 47 e non 48

2022-05-07 08:40 UTC, nicoalbe commented on docs/esterni/piano_di_progetto/piano_di_progetto.tex
> +        Responsabile    & 30 & 11 (+5)  & 330 (+180) \\
11 è +6 dal preventivo

2022-05-07 08:50 UTC, nicoalbe commented on docs/esterni/piano_di_progetto/piano_di_progetto.tex
> +\ganttbar[progress=75]{Manuale Installazione}{2022-03-30}{2022-05-04} \\
Forse la data fine man.install. andrebbe spostata

2022-05-07 09:23 UTC, nicoalbe approved these changes
Ok

2022-05-07 09:24 UTC, merged