Aggiunto parte PB piano progetto e qualifica
iota97/WinningSoftwareSolution pull request #60
Opened 2022-03-01 08:45 UTC by avolpe1998

2022-03-01 23:06 UTC, EliaScandaletti requested changes

2022-03-01 23:06 UTC, EliaScandaletti commented on docs/esterni/piano_di_progetto/piano_di_progetto.tex
> +\paragraph{Test Automatici WebApp (PB)}
Mancano i test per server e contratto

2022-03-01 23:06 UTC, EliaScandaletti commented on docs/esterni/piano_di_qualifica/piano_di_qualifica.tex
> +	26/2/2022 & \pbox{20cm}{Verificare la possibilità di test automatici del JS utente \\tramite jest} & ?\\\hline
Questo dovrebbe essere il codice del server, non il codice utente

2022-03-01 23:06 UTC, EliaScandaletti commented on docs/esterni/piano_di_progetto/piano_di_progetto.tex
> +\subsection{PB}
Manca la parte di sviluppo del prodotto

2022-03-23 14:38 UTC, avolpe1998 commented
@iota97  Si può eliminare questa PR ora che abbiamo ristrutturato il modo in cui facciamo PDP e PDQ?

2022-03-23 14:42 UTC, avolpe1998 commented
Modifiche al PDP e PDQ obsolete

2022-03-23 14:42 UTC, closed without merging